spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/deneme}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  emotion:
    url: "http://127.0.0.1:8099/predict"
    min-confidence: 0.35
  openai:
    api-key: ${OPENAI_API_KEY}
    chat-model: gpt-4o-mini
    embedding-model: text-embedding-3-small
    transcription-model: whisper-1 # <-- YENİ
    speech-model: tts-1            # <-- YENİ
  etl:
    cs-sakarya:
      test-mode: false   # false = tüm sayfalar, true = sadece ilk sayfa
      max-pages: 200     # güvenlik üst sınır
      sleep-ms: 300      # istekler arası bekleme
    ogrwebmail-sss:
      base-url: https://ogrwebmail.sakarya.edu.tr
      menu-url: https://ogrwebmail.sakarya.edu.tr   # ana sayfa da olur (menü orada)
      category-ids: "2,13,14,15,7,4,3,5,16"
      test-mode: false
      max-items: 2000
      sleep-ms: 200
  chroma:
    url: ${CHROMA_URL:http://localhost:8000}  # RAG (vektör veritabanı) için

# application.yaml
jwt:
  secret: ${JWT_SECRET}        # .env / ortam değişkeninden gelir
  exp-min: ${JWT_EXP_MIN:60}   # dakikayla süre (varsayılan 60)
